version: "2.15.1"
services: 
  python:
    build: ./python
    container_name: api_c
    # ports:
    #   - '4000:4000'
    # volumes:
    #   - ./api:/app
  
  mysql_db:
    build: ./mysql
    container_name: mysql_c
    ports:
      - 3306:3306